# Generated by Django 5.1 on 2024-08-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_todolist_tasks_alter_todolist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='Tasks',
        ),
    ]
