# Generated by Django 5.1 on 2024-08-09 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Todo_list',
        ),
    ]
