# Generated by Django 5.1 on 2024-08-09 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_todo_list'),
        ('todo_list', '0003_remove_todolist_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='todo_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='todo_list.todolist'),
        ),
    ]
